# Generated by Django 5.1.1 on 2025-09-03 15:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Допустимы только буквы, цифры и символы . @ + - _', regex='^[\\w.@+-]+\\Z'), django.core.validators.RegexValidator(message='Использование "me" в качестве username запрещено.', regex='^(?!me$).*$')], verbose_name='Имя пользователя'),
        ),
    ]
